### ISSUE TITLE
    ImportError: cannot import name 'Feature' from 'setuptools' 

### ISSUE THREAD

**Issue by fengweiyuan** [Netflix/flamescope#120]
ERROR: Command errored out with exit status 1:
     command: /Users/fwy/env/ksdb/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p3/88pf4865713bvhx1g0qq07980000gn/T/pip-install-n_c6hrko/markupsafe_f7a88688051645a9b3bb18103afea1ba/setup.py'"'"'; __file__='"'"'/private/var/folders/p3/88pf4865713bvhx1g0qq07980000gn/T/pip-install-n_c6hrko/markupsafe_f7a88688051645a9b3bb18103afea1ba/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/p3/88pf4865713bvhx1g0qq07980000gn/T/pip-pip-egg-info-mabo4a6b
         cwd: /private/var/folders/p3/88pf4865713bvhx1g0qq07980000gn/T/pip-install-n_c6hrko/markupsafe_f7a88688051645a9b3bb18103afea1ba/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p3/88pf4865713bvhx1g0qq07980000gn/T/pip-install-n_c6hrko/markupsafe_f7a88688051645a9b3bb18103afea1ba/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/Users/fwy/env/ksdb/lib/python3.8/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by priithaamer** [comment]
Temporary workaround was to install

```
pip3 install setuptools==45
```

**Comment by dougch** [comment]
bumping MarkupSafe to version `1.1` in requirements.txt also works, PR?

**Comment by pashminacameron** [comment]
Same here, `MarkupSafe=1.1` works. 
I also needed to `pip install python-magic-bin==0.4.14` for a successful server start (got a `ImportError: failed to find libmagic.  Check your installation` upon using `python run.py`).  

Working `environment.yml`:
```
name: flame-env
channels:
  - defaults
dependencies:
  - pip<20.3
  - python==3.7.7
  - pip:
    - cachetools==3.0.0
    - click==6.7
    - Flask==1.0
    - itsdangerous==0.24
    - Jinja2==2.10
    - MarkupSafe==1.1.0
    - protobuf==3.6.1
    - python-magic==0.4.15
    - six==1.12.0
    - Werkzeug==0.15.3
    - nflxprofile==1.4.1
    - python-magic-bin==0.4.14
```

**Comment by spiermar** [comment]
Fixed on https://github.com/Netflix/flamescope/commit/44506f957528db4d107a64c889f9f335e97a9e43.
