### ISSUE TITLE
metric other than sample count

### ISSUE THREAD

**Issue by ceeaspb** [Netflix/flamescope#23]
Thanks, great tool.

It would be interesting to have the heat map present other metrics than cpu sample count.

For example throughput and especially some latency statistic (eg median, 99th etc).

The data would come from elsewhere so would need to follow some predefined format, at the right interval.

Expect It likely not be possible to collect this kind of data from production systems. Test/ Benchmark systems may be able to though.

It might be a problem to marry up the perf kernel timestamps to userspace timestamps. it might fall on the perf record end to get the right clock.
```
$ perf record -h 2>&1|grep -i clock
    -k, --clockid <clockid>
                          clockid to use for events, see clock_gettime()```

**Comment by spiermar** [comment]
Thanks for the suggestion @ceeaspb ! We already did it with a few other metrics internally and might be able to share something in the future.
In cases like that, what worked for us is adding a `tools` directory in the repo, with scripts to collect the data and format it in a way FlameScope can understand. If you have something specific in mind, we're open to PRs.

**Comment by spiermar** [comment]
New profile formats should resolve this issue. See https://github.com/Netflix/flamescope/issues/69 for details. Closing to centralize discussion.
