### ISSUE TITLE
overlapping count labels on short record

### ISSUE THREAD

**Issue by ceeaspb** [Netflix/flamescope#25]
minor ui issue with duration of around 10 seconds

<img width="122" alt="screen shot 2018-04-08 at 19 09 13" src="https://user-images.githubusercontent.com/7397675/38470830-63daee02-3b60-11e8-830a-e580c5736fba.png">

**Comment by spiermar** [comment]
@ceeaspb assuming there are 5 ticks in the label, 0, 50, 100, 150, 200 and 250, correct?

**Comment by spiermar** [comment]
Can you try with master @ceeaspb?

**Comment by spiermar** [comment]
Just tested with a short profile, still needs a few more tweaks.

**Comment by spiermar** [comment]
Latest should be better.

**Comment by ceeaspb** [comment]
@spiermar looks great thanks!
