### ISSUE TITLE
Enable Settings view for UI controls

### ISSUE THREAD

**Issue by nhick** [Netflix/flamescope#42]
With more requests coming through for enhanced controls (#39 , #2 , #30 , ...), we should look at enabling the settings view or some other UI component and push some/all of the UI controls there that modify the view.

**Comment by spiermar** [comment]
I have a commented out modal window in the heatmap view. A simple button on top that opens a modal with the UI options for that view. Is that what you have in mind @nhick ?

**Comment by nhick** [comment]
Yes, that's perfect @spiermar .
Created the issue to pr against and use it to discuss what to move into the settings view and what to leave out.

**Comment by spiermar** [comment]
Ok, so I made that assuming that one day we would have more options. The drawback of this solution is that it requires two user actions to get something done, opening the modal and then changing what's required, which can be a pain if you switch things a lot. Right now, I don't think we have too many options in the toolbar, that would cause issues for users, so my suggestion would be to keep it that way until we reach this point, then migrate to the modal solution. Open to counter-arguments.

**Comment by spiermar** [comment]
Yes, I agree.
