### ISSUE TITLE
Flamescope dashboard not available

### ISSUE THREAD

**Issue by PawanWagh** [Netflix/flamescope#43]
I had followed all steps as stated in README. Still not able to view dashboard.
Please find the screenshots below:
![screen shot 2018-04-14 at 11 32 46 am](https://user-images.githubusercontent.com/20369259/38765053-2ecb6774-3fd8-11e8-9e6b-58d372577a5d.png)
Here of dashboard:
![imageedit_2_7523124955](https://user-images.githubusercontent.com/20369259/38765131-a54f0116-3fd9-11e8-82d2-027147814fd8.jpg)
Port Number: 5000 is open & whitelisted for any ip address.
I am running the flamescope tool on my ec2 instance.

**Comment by spiermar** [comment]
The error is pretty clear, your browser can't connect to the server, but there are several possible explanations. Here are a few troubleshooting steps:

1. Can you curl to localhost on port 5000?
2. You mentioned whitelisted? Whitelisted where? iptables? Security group?
3. You are listening on 127.0.0.1 too, which is likely not your external interface. Can you try switching that to 0.0.0.0? Or your external interface ip address?

**Comment by brendangregg** [comment]
I'm guessing you're running flamescope on a remote instance. In which case 127.0.0.1 won't work: you'll need the IP address of that instance. Maybe we should update the startup messages of flamescope to list the remote IP address.

**Comment by spiermar** [comment]
@PawanWagh assuming the issue was fixed. Closing.

**Comment by PawanWagh** [comment]
Hey guys, thanks for the help. Setting host to "0.0.0.0" fixed the problem.
