### ISSUE TITLE
Ability to view Golang graphs

### ISSUE THREAD

**Issue by richardartoul** [Netflix/flamescope#5]
This tool looks really awesome and I'd like to try it out on some profiles taken from our production services, but the tool seems to be having trouble with profiles generated using the `go tool pprof` command.

Has anyone tried or gotten this to work with Golang profiles yet?

Here's the stacktrace I'm getting:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/richardartoul/Documents/flamescope/app/views/heatmap.py", line 34, in get_heatmap
    return jsonify(generate_heatmap(filename, rows))
  File "/Users/richardartoul/Documents/flamescope/app/util/heatmap.py", line 120, in generate_heatmap
    cols = int(ceil(end) - floor(start))
OverflowError: cannot convert float infinity to integer
```

EDIT: Ah ok it looks like this tool is designed to handle the linux perf output whereas golang generates pprof-formatted files.

**Comment by Liron24** [comment]
Hi, I'm getting the same stacktrace and I'm running Java application, any ideas about it?

**Comment by spiermar** [comment]
Ok, so the previous issue was that the trace was generated from trying to open a non-perf profile. Can you share profile with us to reproduce?

**Comment by Liron24** [comment]
@spiermar it's our production application, is there any other information I can provide you to understand what's going on? Or any other instructions for me to try and troubleshoot this?

**Comment by spiermar** [comment]
@Liron24 if it's that exact error

```
cols = int(ceil(end) - floor(start))
OverflowError: cannot convert float infinity to integer
```

Likely the error is caused by a failure to parse a start and/or end timestamps of the profile:

https://github.com/Netflix/flamescope/blob/master/app/util/heatmap.py#L84

If you compare your profile with the examples in the repo, do they look similar? Same format?

**Comment by Liron24** [comment]
@spiermar my generated perf.data is a binary and I can't really read it while the other examples I can clearly open and read. Is there any other command to generate a profile to be similar to the examples?

**Comment by spiermar** [comment]
Ok, so looks like you're trying to open the raw `perf record` data, not the output of `perf script`, which it's text format.

**Comment by Liron24** [comment]
@spiermar you were right. I managed to view an heat map of the stacks output, however, all the classes shows as "unknown", could it stems from the errors I got when creating the stacks? 
`Failed to open <> , continuing without symbols`

**Comment by spiermar** [comment]
Yes, unknowns are missing symbols.

**Comment by felixge** [comment]
It's now possible to use FlameScope with go1.19+ - I've written a tool and blog post for it here: https://blog.felixge.de/flamescope-for-go/
