### ISSUE TITLE
support for trace event format

### ISSUE THREAD

**Issue by Leland-Takamine** [Netflix/flamescope#51]
Support for opening a [Chrome trace file](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU) for example would allow other profiling tools to integrate with FlameScope. Context: We've built our own visualization for [Nanoscope](https://github.com/uber/nanoscope), but it would be nice to have an option to view the data in FlameScope.

**Comment by spiermar** [comment]
@Leland-Takamine can you open a new issue for Nanoscope and provide a trace sample?

**Comment by Leland-Takamine** [comment]
@spiermar The idea would be that Nanoscope would generate a chrome trace file output to interop with this tool.

**Comment by spiermar** [comment]
@Leland-Takamine Even better. It's in the backlog. If we don't get any volunteers for this, I'll pick it up once I get a bit of time.

**Comment by spiermar** [comment]
Done
