### ISSUE TITLE
support for differential flame graphs

### ISSUE THREAD

**Issue by spiermar** [Netflix/flamescope#57]

**Comment by avisrivastava254084** [comment]
@spiermar , can you explain this issue a bit? Or could you redirect me to sources reading which would make me understand?

I want to contribute.

**Comment by spiermar** [comment]
@avisrivastava254084 already solved in the [feat_differential_flame_graphs](https://github.com/Netflix/flamescope/tree/feat_differential_flame_graphs) branch. Just need to run a few tests before merging into master. In a nutshell, the new feature adds support for comparing flame graphs through differential flame graphs. If are looking to start contributing, two issues we are actively looking right now are https://github.com/Netflix/flamescope/issues/69 and https://github.com/Netflix/flamescope/issues/39. Happy to share more details about it.

**Comment by mboussaa** [comment]
@spiermar I hit the following error from the feat_differential_flame_graphs branch when running python run.py. Any idea why? Thanks
```
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from app import APP
  File "/home/mboussaa/flamescope/app/__init__.py", line 34, in <module>
    from app.views.flame_graph import MOD_FLAME_GRAPH
  File "/home/mboussaa/flamescope/app/views/flame_graph.py", line 21, in <module>
    from app.controllers.flame_graph import generate_flame_graph
  File "/home/mboussaa/flamescope/app/controllers/flame_graph.py", line 25, in <module>
    from app.trace_event.flame_graph import trace_event_generate_flame_graph
  File "/home/mboussaa/flamescope/app/trace_event/flame_graph.py", line 26, in <module>
    from json.decoder import JSONDecodeError
ImportError: cannot import name JSONDecodeError
```

**Comment by spiermar** [comment]
No need to use the branch anymore. It was already merged into master. And the issue was caused by the python version you are using.
