### ISSUE TITLE
master `Dockerfile` is broken

### ISSUE THREAD

**Issue by nobeh** [Netflix/flamescope#66]
Recent refactorings specifically b496f7787c52550fc3dc072ba538bcdc86f5e8d7 seems to have bumped the required Python from 2.7 to 3.6. In addition, `libmagic` is assumed to be installed for Python binding. These are not yet updated in `Dockerfile`; the following patch seems to fix the problem until a fix is merged:

```diff
diff --git a/Dockerfile b/Dockerfile
index e4c1346..23cba5c 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,11 +1,12 @@
-FROM python:2-alpine3.7
+FROM python:3-alpine3.8
 
 ADD app /app/app
 ADD run.py /app
 ADD requirements.txt /app
 
-RUN cd /app && \
-  pip install -r requirements.txt && \
+RUN apk add libmagic && \
+  cd /app && \ \
+  pip3 install -r requirements.txt && \
   mkdir /profiles && \
   sed -i -e s/127.0.0.1/0.0.0.0/g -e s~examples~/profiles~g app/config.py
```

**Side Note** It would be great if there would be tags on the repo so that community could rely on a working version.

**Comment by rahulsh1** [comment]
There is a typo in your PR. 
`  cd /app && \ \` should be

`  cd /app && \ `

Otherwise it throws the misleading `/bin/sh:  : not found`
Thanks for providing a working version :+1:

**Comment by spiermar** [comment]
Yepp, forgot to add that recently. Will add shortly.
