### ISSUE TITLE
The application lacks protection against CSRF

### ISSUE THREAD

**Issue by atx** [Netflix/flamescope#7]
The application lacks any sort of protection against CSRF (let alone DNS rebinding).

As some, uhhh, creative development time saving techniques are [used](https://github.com/Netflix/flamescope/blob/master/app/util/stack.py#L163), an attacker can execute arbitrary shell commands on the computer running this software by redirecting the users browser to something like:

```
<a href="http://127.0.0.1:5000/stack/?filename=%3Bxcalc%3Bfoo.gz">Link</a>
```

**Comment by brendangregg** [comment]
Thanks @atx! I've fixed the filename escapes. We still need to look at the CSRF and DNS rebinding.

**Comment by spiermar** [comment]
@brendangregg recent PR merge might have fixed a few of those issues.

**Comment by spiermar** [comment]
Assuming this was fixed. Closing.
