### ISSUE TITLE
flamescope failing to render flamegraph

### ISSUE THREAD

**Issue by prateekr** [Netflix/flamescope#77]
GIT TAG=91bc199
OS: Mac
Browser: Chrome

The heatmap page works, but on the flamegraph page, the flamegraph itself fails to load.  I see the following error in the javascript console:

```
main.js:33 Uncaught TypeError: Cannot read property 'bind' of undefined
    at main.js:50
    at Array.forEach (<anonymous>)
    at new e (main.js:50)
    at zr (main.js:33)
    at ui (main.js:33)
    at fi (main.js:33)
    at Ki (main.js:33)
    at qi (main.js:33)
    at Da (main.js:33)
    at _a (main.js:33)
```
The flamegraph does load on git tag df6700421082890e66cfd8caedf4ebe678ab1068 

The examples provided on the current commit, 91bc199, fail with the same error.

**Comment by wuyihao14** [comment]
Is there any progress on this issue? thx

**Comment by spiermar** [comment]
Not yet. On my backlog.

**Comment by wuyihao14** [comment]
#79

**Comment by prateekr** [comment]
It still fails on chrome on mac.  It does succeed on safari tho.
