### ISSUE TITLE
icicle layout

### ISSUE THREAD

**Issue by brendangregg** [Netflix/flamescope#8]
There could be a button on the flame graph view to switch it to icicle layout. This could be sticky, and/or configured via a settings page, so it always did it this way. I'm not sure what to call the button: I guess the two layout orderings are "flame" and "icicle". (Note that there's also a different layout type, sunburst, which we could also switch to, but that's changing the type of visualization rather than just the ordering; I'll file a separate ticket).

Adding this feature probably means adding code to https://github.com/spiermar/d3-flame-graph .

**Comment by bahtiyarkaba** [comment]
The flame-graph can be configured with an[ inverted flag. ]( https://github.com/spiermar/d3-flame-graph#inverted )  
I have something done with it. I'll submit a PR.  
Please assign the issue to me if that sounds ok.

**Comment by spiermar** [comment]
@bahtiyarkaba I can't assign the issue to you because the rights on the GitHub project, but feel free to submit a PR and I'll review it
